server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tower_deploy_db?useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
      enabled: true
mybatis:
  type-aliases-package: com.sigma.towerdepoyms.entity
  mapper-locations: classpath:mapper/*.xml

ansible:
  path: /deploy/app-packages

git:
  path: G:\git-package
  username: zhenpeng
  password: ''